### ISSUE TITLE
Existing stack advancements not counted even after updating 

### ISSUE THREAD

**Issue by scribblemaniac** [Sir-Chi/QuestForEverything#10]
I recently started a single-player game with Quest for Everything stack edition (1.0), but the scoreboard and progress for partially completed advancements never updated. I can confirm this has now been fixed with 27b348a029eb0a1ae267e797911586d3532d39a8, however only for newly-gained advancements. Any advancements I had already gained prior to the updating the data pack are still marked completed, but uncounted in the scoreboard. The progress for partially completed advancements is similarly broken. While submitting new items for partially completed advancements does update the progress value, it is not updated to the correct value. If all these could update automatically with the correct value, or at least if there was a function that could force these values to be recalculated, that would be appreciated.

**Comment by Sir-Chi** [comment]
As far as I'm aware other than manually granting the advancement and corresponding function, there's no way of updating the values automatically. This issue to the data not having saved correctly prior to updating the pack.

**Comment by scribblemaniac** [comment]
Well it's obviously wrong that the correct data doesn't exist because it knows the correct amount of items I've submitted previously when I try to submit new items. The score is just the number of items where I've submitted 64 total, and the progress is just the number of items submitted itself.

Given that it seems unlikely I'll get any help here, I just spent a day learning how to program datapacks and fixed it myself. For anyone facing the same problem, you can use the version from my fork here: https://github.com/scribblemaniac/QuestForEverything/tree/stack-repair-funcs, which also includes the fixes from #11. After installing that version and restarting Minecraft, you can run `/function qfe:repair/repair_all` and your score and progress for advancements will be updated. If you have already submitted many items and do not get a "Repair complete!" after a few seconds, then you may have to temporarily increase your `maxCommandChainLength` gamerule value with a command like `/gamerule maxCommandChainLength 1000000` (default value is 65536). It has to run several functions for each individual item submitted, so they add up quickly.
