### ISSUE TITLE
Mud Brick Wall

### ISSUE THREAD

**Issue by breon** [Sir-Chi/QuestForEverything#2]
There isn't an advancement for mud brick wall.

**Comment by Sir-Chi** [comment]
Fixed now in release 1.5.3 for both small biome and original versions

**Comment by breon** [comment]
Thanks! Am I able to use this updated data pack with my current play through or will this only work with new playthroughs?

**Comment by Sir-Chi** [comment]
You can update, your current world. There should be no incompatibilities 😄
