### ISSUE TITLE
Mud Brick Wall in Teams mode

### ISSUE THREAD

**Issue by davepusey** [Sir-Chi/QuestForEverything#3]
The advancement for Mud Brick Wall doesn't appear to work correctly in Teams mode. I collected the item, and got the advancement myself, but other team members still show it is outstanding.

Purple team

Running 1.19.0 and using QuestForEverything-v1.5.3-[1.19+]-SmallBiomes

**Comment by Sir-Chi** [comment]
Should be all fixed now, thanks for letting me know! 😄
