### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Namirauuh** [Sir-Chi/QuestForEverything#9]
Hello ! Is it possible to deactivate the fact that it is a race and instead be able to little by little succeed in recovering each item? I would like to be able to deactivate the stopwatch for example for this, and instead have a chill atmosphere instead of a race. Thanks in advance !

**Comment by Sir-Chi** [comment]
Sorry for the late reply, I've been quite tied up with IRL things. The visibility of the timer can be toggled in the start using the showTimer option in the Game Setup book. I'll push an update to github and curseforge with the new 3.0 update which will contain this and other changes.
Again I do apologise for the late reply and thank you for playing!
